/-
  IRONCLAD-QLDPC per-run decode certificate  --  code90_p0_06_s20260905_failure
  Code: code90 ([[90,8,10]])   Outcome claimed: FAILURE
  Auto-generated by impl/certgen.py; checked by the Lean kernel via plain
  `decide` against proofs/DecoderCert.lean (validateRun_sound gives the
  semantic guarantee). Zero axioms, zero sorries, zero native_decide.
-/

import proofs.DecoderCert

set_option maxRecDepth 16384

namespace RunCert_code90_p0_06_s20260905_failure

def theCode : QLDPC.GBCode (Fin 15 × Fin 3) :=
  ⟨⟨({((9 : Fin 15), (0 : Fin 3)), ((0 : Fin 15), (1 : Fin 3)), ((0 : Fin 15), (2 : Fin 3))} : Finset (Fin 15 × Fin 3))⟩,
   ⟨({((0 : Fin 15), (0 : Fin 3)), ((2 : Fin 15), (0 : Fin 3)), ((7 : Fin 15), (0 : Fin 3))} : Finset (Fin 15 × Fin 3))⟩⟩

def observed : Fin 15 × Fin 3 → ZMod 2 :=
  fun g => if g ∈ ({((1 : Fin 15), (1 : Fin 3)), ((2 : Fin 15), (1 : Fin 3)), ((3 : Fin 15), (2 : Fin 3)), ((4 : Fin 15), (0 : Fin 3)), ((5 : Fin 15), (0 : Fin 3)), ((5 : Fin 15), (1 : Fin 3)), ((6 : Fin 15), (1 : Fin 3)), ((7 : Fin 15), (1 : Fin 3)), ((9 : Fin 15), (1 : Fin 3)), ((11 : Fin 15), (0 : Fin 3)), ((11 : Fin 15), (1 : Fin 3)), ((12 : Fin 15), (0 : Fin 3)), ((13 : Fin 15), (2 : Fin 3))} : Finset (Fin 15 × Fin 3)) then 1 else 0

def correction : QLDPC.QubitVec (Fin 15 × Fin 3) :=
  (fun g => if g ∈ ({((3 : Fin 15), (1 : Fin 3)), ((9 : Fin 15), (1 : Fin 3)), ((11 : Fin 15), (0 : Fin 3)), ((13 : Fin 15), (2 : Fin 3))} : Finset (Fin 15 × Fin 3)) then 1 else 0,
     fun g => if g ∈ ({((3 : Fin 15), (0 : Fin 3)), ((5 : Fin 15), (2 : Fin 3)), ((6 : Fin 15), (0 : Fin 3))} : Finset (Fin 15 × Fin 3)) then 1 else 0)

def injected : QLDPC.QubitVec (Fin 15 × Fin 3) :=
  (fun g => if g ∈ ({((1 : Fin 15), (1 : Fin 3)), ((13 : Fin 15), (1 : Fin 3)), ((14 : Fin 15), (1 : Fin 3))} : Finset (Fin 15 × Fin 3)) then 1 else 0,
     fun g => if g ∈ ({((5 : Fin 15), (2 : Fin 3)), ((11 : Fin 15), (1 : Fin 3)), ((12 : Fin 15), (2 : Fin 3)), ((13 : Fin 15), (0 : Fin 3))} : Finset (Fin 15 × Fin 3)) then 1 else 0)

def outcomeWitness : (Fin 15 × Fin 3 → ZMod 2) ⊕ QLDPC.QubitVec (Fin 15 × Fin 3) :=
  Sum.inr (fun g => if g ∈ ({((1 : Fin 15), (0 : Fin 3)), ((1 : Fin 15), (2 : Fin 3)), ((4 : Fin 15), (0 : Fin 3)), ((4 : Fin 15), (2 : Fin 3)), ((7 : Fin 15), (0 : Fin 3)), ((7 : Fin 15), (2 : Fin 3)), ((10 : Fin 15), (0 : Fin 3)), ((10 : Fin 15), (2 : Fin 3)), ((13 : Fin 15), (0 : Fin 3)), ((13 : Fin 15), (2 : Fin 3))} : Finset (Fin 15 × Fin 3)) then 1 else 0,
     fun _ => (0 : ZMod 2))

def run : QLDPC.DecoderCert.DecodeRunCert (Fin 15 × Fin 3) :=
  ⟨observed, correction, injected, outcomeWitness⟩

-- The kernel-checked fact. By validateRun_sound this certifies dense syndrome
-- consistency of both vectors, residual ∈ ker H_Z, AND the claimed logical
-- outcome of the residual. Named so `#print axioms` audits THIS certificate.
theorem cert_valid : QLDPC.DecoderCert.validateRun theCode run = true := by
  decide

#print axioms cert_valid

end RunCert_code90_p0_06_s20260905_failure
