/-
  IRONCLAD-QLDPC per-run decode certificate  --  code72_p0_03_s999_success
  Code: code72 ([[72,12,6]])   Outcome claimed: SUCCESS
  Auto-generated by impl/certgen.py; checked by the Lean kernel via plain
  `decide` against proofs/DecoderCert.lean (validateRun_sound gives the
  semantic guarantee). Zero axioms, zero sorries, zero native_decide.
-/

import proofs.DecoderCert

set_option maxRecDepth 16384

namespace RunCert_code72_p0_03_s999_success

-- code instance: QLDPC.code72 (defined in proofs/BBCode.lean)

def observed : Fin 6 × Fin 6 → ZMod 2 :=
  fun _ => (0 : ZMod 2)

def correction : QLDPC.QubitVec (Fin 6 × Fin 6) :=
  (fun _ => (0 : ZMod 2),
     fun _ => (0 : ZMod 2))

def injected : QLDPC.QubitVec (Fin 6 × Fin 6) :=
  (fun _ => (0 : ZMod 2),
     fun _ => (0 : ZMod 2))

def outcomeWitness : (Fin 6 × Fin 6 → ZMod 2) ⊕ QLDPC.QubitVec (Fin 6 × Fin 6) :=
  Sum.inl (fun _ => (0 : ZMod 2))

def run : QLDPC.DecoderCert.DecodeRunCert (Fin 6 × Fin 6) :=
  ⟨observed, correction, injected, outcomeWitness⟩

-- The kernel-checked fact. By validateRun_sound this certifies dense syndrome
-- consistency of both vectors, residual ∈ ker H_Z, AND the claimed logical
-- outcome of the residual. Named so `#print axioms` audits THIS certificate.
theorem cert_valid : QLDPC.DecoderCert.validateRun QLDPC.code72 run = true := by
  decide

#print axioms cert_valid

end RunCert_code72_p0_03_s999_success
