/-
  IRONCLAD-QLDPC per-run decode certificate  --  gross144_p0_06_s20260905_failure
  Code: gross144 ([[144,12,12]])   Outcome claimed: FAILURE
  Auto-generated by impl/certgen.py; checked by the Lean kernel via plain
  `decide` against proofs/DecoderCert.lean (validateRun_sound gives the
  semantic guarantee). Zero axioms, zero sorries, zero native_decide.
-/

import proofs.DecoderCert

set_option maxRecDepth 16384

namespace RunCert_gross144_p0_06_s20260905_failure

-- code instance: QLDPC.grossCode (defined in proofs/BBCode.lean)

def observed : Fin 12 × Fin 6 → ZMod 2 :=
  fun g => if g ∈ ({((0 : Fin 12), (5 : Fin 6)), ((1 : Fin 12), (2 : Fin 6)), ((1 : Fin 12), (3 : Fin 6)), ((2 : Fin 12), (2 : Fin 6)), ((3 : Fin 12), (1 : Fin 6)), ((4 : Fin 12), (0 : Fin 6)), ((4 : Fin 12), (4 : Fin 6)), ((5 : Fin 12), (3 : Fin 6)), ((6 : Fin 12), (3 : Fin 6)), ((6 : Fin 12), (4 : Fin 6)), ((7 : Fin 12), (4 : Fin 6)), ((7 : Fin 12), (5 : Fin 6)), ((8 : Fin 12), (3 : Fin 6)), ((8 : Fin 12), (4 : Fin 6)), ((9 : Fin 12), (2 : Fin 6)), ((9 : Fin 12), (3 : Fin 6)), ((10 : Fin 12), (0 : Fin 6)), ((10 : Fin 12), (2 : Fin 6)), ((10 : Fin 12), (4 : Fin 6)), ((11 : Fin 12), (0 : Fin 6)), ((11 : Fin 12), (2 : Fin 6)), ((11 : Fin 12), (5 : Fin 6))} : Finset (Fin 12 × Fin 6)) then 1 else 0

def correction : QLDPC.QubitVec (Fin 12 × Fin 6) :=
  (fun g => if g ∈ ({((0 : Fin 12), (2 : Fin 6)), ((0 : Fin 12), (3 : Fin 6)), ((2 : Fin 12), (5 : Fin 6)), ((4 : Fin 12), (0 : Fin 6)), ((6 : Fin 12), (0 : Fin 6)), ((7 : Fin 12), (3 : Fin 6)), ((8 : Fin 12), (0 : Fin 6)), ((9 : Fin 12), (4 : Fin 6)), ((10 : Fin 12), (1 : Fin 6)), ((10 : Fin 12), (3 : Fin 6))} : Finset (Fin 12 × Fin 6)) then 1 else 0,
     fun g => if g ∈ ({((0 : Fin 12), (1 : Fin 6)), ((1 : Fin 12), (4 : Fin 6)), ((2 : Fin 12), (2 : Fin 6)), ((4 : Fin 12), (5 : Fin 6)), ((5 : Fin 12), (1 : Fin 6)), ((6 : Fin 12), (0 : Fin 6)), ((6 : Fin 12), (1 : Fin 6)), ((8 : Fin 12), (5 : Fin 6)), ((9 : Fin 12), (3 : Fin 6)), ((10 : Fin 12), (5 : Fin 6)), ((11 : Fin 12), (1 : Fin 6)), ((11 : Fin 12), (4 : Fin 6))} : Finset (Fin 12 × Fin 6)) then 1 else 0)

def injected : QLDPC.QubitVec (Fin 12 × Fin 6) :=
  (fun g => if g ∈ ({((1 : Fin 12), (0 : Fin 6)), ((4 : Fin 12), (1 : Fin 6)), ((7 : Fin 12), (3 : Fin 6)), ((8 : Fin 12), (4 : Fin 6)), ((10 : Fin 12), (1 : Fin 6)), ((10 : Fin 12), (3 : Fin 6)), ((11 : Fin 12), (2 : Fin 6))} : Finset (Fin 12 × Fin 6)) then 1 else 0,
     fun g => if g ∈ ({((0 : Fin 12), (1 : Fin 6)), ((2 : Fin 12), (3 : Fin 6)), ((4 : Fin 12), (2 : Fin 6)), ((7 : Fin 12), (1 : Fin 6)), ((11 : Fin 12), (4 : Fin 6))} : Finset (Fin 12 × Fin 6)) then 1 else 0)

def outcomeWitness : (Fin 12 × Fin 6 → ZMod 2) ⊕ QLDPC.QubitVec (Fin 12 × Fin 6) :=
  Sum.inr (fun g => if g ∈ ({((0 : Fin 12), (0 : Fin 6)), ((0 : Fin 12), (1 : Fin 6)), ((0 : Fin 12), (2 : Fin 6)), ((0 : Fin 12), (5 : Fin 6)), ((3 : Fin 12), (0 : Fin 6)), ((3 : Fin 12), (4 : Fin 6)), ((6 : Fin 12), (0 : Fin 6)), ((6 : Fin 12), (1 : Fin 6)), ((6 : Fin 12), (2 : Fin 6)), ((6 : Fin 12), (5 : Fin 6)), ((9 : Fin 12), (0 : Fin 6)), ((9 : Fin 12), (4 : Fin 6))} : Finset (Fin 12 × Fin 6)) then 1 else 0,
     fun _ => (0 : ZMod 2))

def run : QLDPC.DecoderCert.DecodeRunCert (Fin 12 × Fin 6) :=
  ⟨observed, correction, injected, outcomeWitness⟩

-- The kernel-checked fact. By validateRun_sound this certifies dense syndrome
-- consistency of both vectors, residual ∈ ker H_Z, AND the claimed logical
-- outcome of the residual. Named so `#print axioms` audits THIS certificate.
theorem cert_valid : QLDPC.DecoderCert.validateRun QLDPC.grossCode run = true := by
  decide

#print axioms cert_valid

end RunCert_gross144_p0_06_s20260905_failure
