/-
# BBCode — Two-Block Group-Algebra Quantum Codes, Verified Parametrically

IRONCLAD-QLDPC extension, file F2. 2026-07-05.

## Purpose

Formalizes the CSS structure of two-block abelian group-algebra codes: parity
checks `H_X = [A | B]`, `H_Z = [Bᵀ | Aᵀ]` with `A, B` circulant over a finite
abelian group `G`. This family includes:

- **generalized bicycle codes** (`G = ZMod n`), and
- **bivariate bicycle (BB) codes** (`G = Fin ℓ × Fin m`), e.g. IBM's
  [[144,12,12]] "gross" code (Bravyi et al., Nature 627, 2024).

## Main results

- `GBCode.css_ZX` / `GBCode.css_XZ` (**T2, map form**): every X-stabilizer has
  zero Z-syndrome and vice versa — CSS validity for the ENTIRE family at once,
  parametric in `G`, `a`, `b`. The proof is exactly the commutativity of the
  circulant algebra (`Matrix.circulant_mul_comm`) plus characteristic 2.
- `GBCode.css_matrix` (**T2, dense form**): `H_X * H_Zᵀ = 0`.
- `GBCode.syndromeX_eq_dense` / `syndromeZ_eq_dense`: the sparse syndrome maps
  (what a fast checker computes) provably equal the dense parity-check action —
  the family-level ground-truth bridge for the decoder certificate layer.
- `GBCode.syndromeX_translate` / `syndromeZ_translate` (**T3**): syndrome maps
  commute with the `|G|` qubit translations — the group-theoretic content behind
  block-diagonalizability of quasi-cyclic checks.
- `grossCode`, `code72`: concrete BB instances with kernel-checked sanity facts.

## Relation to prior art (claims discipline)

Lean-QEC (2026) formalized BB codes for *static distance certification*; this
file's role in IRONCLAD-QLDPC is different: it provides the parametric CSS/
equivariance layer that the *decoder-output certificate* files build on. We
claim "machine-checked for the whole family, in four lines of algebra", not
"first formalization of BB codes". Zero sorries, zero axioms, no native_decide.
-/

import Mathlib
import proofs.QCCirculant

open Matrix Finset QCCirculant

namespace QLDPC

variable {G : Type*} [AddCommGroup G] [Fintype G] [DecidableEq G]

/-- A two-block abelian group-algebra code, given by two sparse polynomials
    `a, b` over `F₂[G]`. Qubits: two blocks indexed by `G` (n = 2|G|).
    X-checks: rows of `[A | B]`; Z-checks: rows of `[Bᵀ | Aᵀ]`. -/
structure GBCode (G : Type*) where
  /-- Left-block polynomial (support of the circulant `A`). -/
  a : SparsePoly G
  /-- Right-block polynomial (support of the circulant `B`). -/
  b : SparsePoly G

/-- A vector on the data qubits: one F₂ function per block. -/
abbrev QubitVec (G : Type*) := (G → ZMod 2) × (G → ZMod 2)

namespace GBCode

variable (c : GBCode G)

/-! ## Section 1: Dense and sparse forms of the parity-check action -/

/-- The dense circulant block `A`. -/
def Amat : Matrix G G (ZMod 2) := Matrix.circulant c.a.toVec

/-- The dense circulant block `B`. -/
def Bmat : Matrix G G (ZMod 2) := Matrix.circulant c.b.toVec

/-- Dense X parity-check matrix `H_X = [A | B]`. -/
def HX : Matrix G (G ⊕ G) (ZMod 2) := Matrix.fromCols c.Amat c.Bmat

/-- Dense Z parity-check matrix `H_Z = [Bᵀ | Aᵀ]`. -/
def HZ : Matrix G (G ⊕ G) (ZMod 2) := Matrix.fromCols c.Bmatᵀ c.Amatᵀ

/-- Sparse X-syndrome map (detects Z-type errors): `s = A·f₁ + B·f₂`.
    Cost per syndrome bit: row weight — this is what a fast checker computes. -/
def syndromeX (f : QubitVec G) : G → ZMod 2 :=
  c.a.mulVecS f.1 + c.b.mulVecS f.2

/-- Sparse Z-syndrome map (detects X-type errors): `s = Bᵀ·e₁ + Aᵀ·e₂`. -/
def syndromeZ (e : QubitVec G) : G → ZMod 2 :=
  c.b.mulVecT e.1 + c.a.mulVecT e.2

/-- X-stabilizer application `H_Xᵀ w`: the X-type operator generated by the
    check-combination `w`. -/
def xStab (w : G → ZMod 2) : QubitVec G :=
  (c.a.mulVecT w, c.b.mulVecT w)

/-- Z-stabilizer application `H_Zᵀ v`. -/
def zStab (v : G → ZMod 2) : QubitVec G :=
  (c.b.mulVecS v, c.a.mulVecS v)

/-! ## Section 2: Sparse = dense (ground-truth bridge) -/

/-- The sparse X-syndrome map equals the dense parity-check action `H_X · f`. -/
theorem syndromeX_eq_dense (f : QubitVec G) :
    c.syndromeX f = c.HX.mulVec (Sum.elim f.1 f.2) := by
  unfold syndromeX HX
  rw [Matrix.fromCols_mulVec_sumElim, SparsePoly.mulVecS_eq_mulVec,
      SparsePoly.mulVecS_eq_mulVec]
  rfl

/-- The sparse Z-syndrome map equals the dense parity-check action `H_Z · e`. -/
theorem syndromeZ_eq_dense (e : QubitVec G) :
    c.syndromeZ e = c.HZ.mulVec (Sum.elim e.1 e.2) := by
  unfold syndromeZ HZ
  rw [Matrix.fromCols_mulVec_sumElim, SparsePoly.mulVecT_eq_mulVec,
      SparsePoly.mulVecT_eq_mulVec]
  rfl

/-- The sparse stabilizer application equals the dense `H_Xᵀ · w`. -/
theorem xStab_eq_dense (w : G → ZMod 2) :
    Sum.elim (c.xStab w).1 (c.xStab w).2 = c.HXᵀ.mulVec w := by
  unfold xStab HX Amat Bmat
  rw [Matrix.transpose_fromCols, Matrix.fromRows_mulVec,
      SparsePoly.mulVecT_eq_mulVec, SparsePoly.mulVecT_eq_mulVec]

/-! ## Section 3: CSS validity — the whole family at once (T2) -/

/-- **T2 (CSS validity, Z∘X form)**: every X-stabilizer has zero Z-syndrome.
    Parametric in `G`, `a`, `b`: this single theorem covers every generalized
    bicycle and bivariate bicycle code. The content is precisely the
    commutativity of the circulant algebra + characteristic 2. -/
theorem css_ZX (w : G → ZMod 2) : c.syndromeZ (c.xStab w) = 0 := by
  unfold syndromeZ xStab
  simp only [SparsePoly.mulVecT_eq_mulVec, Matrix.mulVec_mulVec]
  rw [← Matrix.transpose_mul, ← Matrix.transpose_mul, Matrix.circulant_mul_comm]
  funext g
  simp only [Pi.add_apply, Pi.zero_apply]
  exact CharTwo.add_self_eq_zero _

/-- **T2 (CSS validity, X∘Z form)**: every Z-stabilizer has zero X-syndrome. -/
theorem css_XZ (v : G → ZMod 2) : c.syndromeX (c.zStab v) = 0 := by
  unfold syndromeX zStab
  simp only [SparsePoly.mulVecS_eq_mulVec, Matrix.mulVec_mulVec]
  rw [Matrix.circulant_mul_comm]
  funext g
  simp only [Pi.add_apply, Pi.zero_apply]
  exact CharTwo.add_self_eq_zero _

/-- **T2 (CSS validity, dense matrix form)**: `H_X * H_Zᵀ = 0`. -/
theorem css_matrix : c.HX * c.HZᵀ = 0 := by
  unfold HX HZ Amat Bmat
  rw [Matrix.transpose_fromCols, Matrix.transpose_transpose, Matrix.transpose_transpose,
      Matrix.fromCols_mul_fromRows, Matrix.circulant_mul_comm]
  ext i j
  simp only [Matrix.add_apply, Matrix.zero_apply]
  exact CharTwo.add_self_eq_zero _

/-! ## Section 4: Translation equivariance (T3) -/

omit [Fintype G] [DecidableEq G] in
/-- **T3**: the X-syndrome map commutes with qubit translations. -/
theorem syndromeX_translate (h : G) (f : QubitVec G) :
    c.syndromeX (QCCirculant.translate h f.1, QCCirculant.translate h f.2) =
      QCCirculant.translate h (c.syndromeX f) := by
  unfold syndromeX
  rw [SparsePoly.mulVecS_translate, SparsePoly.mulVecS_translate]
  funext g
  simp [QCCirculant.translate]

omit [Fintype G] [DecidableEq G] in
/-- **T3**: the Z-syndrome map commutes with qubit translations. -/
theorem syndromeZ_translate (h : G) (e : QubitVec G) :
    c.syndromeZ (QCCirculant.translate h e.1, QCCirculant.translate h e.2) =
      QCCirculant.translate h (c.syndromeZ e) := by
  unfold syndromeZ
  rw [SparsePoly.mulVecT_translate, SparsePoly.mulVecT_translate]
  funext g
  simp [QCCirculant.translate]

end GBCode

/-! ## Section 5: Concrete bivariate bicycle instances -/

/-- IBM's [[144,12,12]] "gross" bivariate bicycle code: `ℓ=12, m=6`,
    `a = x³ + y + y²`, `b = y³ + x + x²` (Bravyi et al., Nature 627, 2024). -/
def grossCode : GBCode (Fin 12 × Fin 6) where
  a := ⟨{(3, 0), (0, 1), (0, 2)}⟩
  b := ⟨{(0, 3), (1, 0), (2, 0)}⟩

/-- The [[72,12,6]] bivariate bicycle code: `ℓ=6, m=6`, same polynomial shape. -/
def code72 : GBCode (Fin 6 × Fin 6) where
  a := ⟨{(3, 0), (0, 1), (0, 2)}⟩
  b := ⟨{(0, 3), (1, 0), (2, 0)}⟩

-- Kernel-checked sanity facts (plain `decide`, no native_decide):
example : grossCode.a.support.card = 3 := by decide
example : grossCode.b.support.card = 3 := by decide
example : code72.a.support.card = 3 := by decide
-- n = 2|G| data qubits:
example : 2 * Fintype.card (Fin 12 × Fin 6) = 144 := by decide
example : 2 * Fintype.card (Fin 6 × Fin 6) = 72 := by decide

end QLDPC
